# Site settings
author: Sean Murphy
title: Sean Murphy's Coding Blog
header-img: img/home-bg.png
email: filmmakersean@fastmail.net
copyright_name: Sean Murphy
description: > # this means to ignore newlines until "baseurl:"
  A technical blog of a new coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  murphcoder

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
